INSERT INTO genres (genre, genre_pt) VALUES ('Historical fiction', 'ficção histórica');
INSERT INTO genres (genre, genre_pt) VALUES ('Novella', 'novela');
INSERT INTO genres (genre, genre_pt) VALUES ('Fantasy', 'fantasia');
INSERT INTO genres (genre, genre_pt) VALUES ('Mystery', 'mistério');
INSERT INTO genres (genre, genre_pt) VALUES ('Family saga', 'saga da família');
INSERT INTO genres (genre, genre_pt) VALUES ('Fantasy, Children''s fiction', 'fantasia, ficção infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('Adventure', 'aventura');
INSERT INTO genres (genre, genre_pt) VALUES ('Detective', 'detetive');
INSERT INTO genres (genre, genre_pt) VALUES ('Mystery thriller', 'thriller misterioso');
INSERT INTO genres (genre, genre_pt) VALUES ('Coming-of-age', 'amadurecimento');
INSERT INTO genres (genre, genre_pt) VALUES ('Romance', 'romance');
INSERT INTO genres (genre, genre_pt) VALUES ('Self-help', 'autoajuda');
INSERT INTO genres (genre, genre_pt) VALUES ('Magic realism', 'realismo mágico');
INSERT INTO genres (genre, genre_pt) VALUES ('Novel', 'romance');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s fiction', 'ficção infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('Manual', 'manual');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s novel', 'romance infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s literature', 'literatura infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('Historical novel, mystery', 'novel histórico, mystery');
INSERT INTO genres (genre, genre_pt) VALUES ('War, thriller', 'guerra, suspense');
INSERT INTO genres (genre, genre_pt) VALUES ('Sexology', 'sexologia');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s Literature', 'literatura infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('Novella, Self-help', 'novella, auto-ajuda');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s Literature, picture book', 'literatura infantil, livro de figuras');
INSERT INTO genres (genre, genre_pt) VALUES ('Essay/Literature', 'ensaio/literatura');
INSERT INTO genres (genre, genre_pt) VALUES ('Southern Gothic, Bildungsroman', 'romance gótico do sul e educacional');
INSERT INTO genres (genre, genre_pt) VALUES ('Gothic horror, Family saga', 'horror gótico, saga da família');
INSERT INTO genres (genre, genre_pt) VALUES ('Popular science, Anthropology, Astrophysics, Cosmology, Philosophy, History', 'ciência popular, antropologia, astrofísica, cosmologia, filosofia, história');
INSERT INTO genres (genre, genre_pt) VALUES ('Philosophical novel, Young adult', 'romance filosófico, jovem adulto');
INSERT INTO genres (genre, genre_pt) VALUES ('Mystery-thriller', 'thriller de mistério');
INSERT INTO genres (genre, genre_pt) VALUES ('Socialist realist novel', 'romance realista socialista');
INSERT INTO genres (genre, genre_pt) VALUES ('Historical novel', 'romance histórico');
INSERT INTO genres (genre, genre_pt) VALUES ('Historical non-fiction, Autobiography, Memoir, Bildungsroman / Coming of Age, Jewish literature', 'não ficção histórica, autobiografia, memórias, bildungsroman / withing of age, literatura judaica');
INSERT INTO genres (genre, genre_pt) VALUES ('Romantic family saga', 'saga da família romântica');
INSERT INTO genres (genre, genre_pt) VALUES ('Christian literature', 'literatura cristã');
INSERT INTO genres (genre, genre_pt) VALUES ('Bildungsroman, Historical fiction', 'romance educacional, ficção histórica');
INSERT INTO genres (genre, genre_pt) VALUES ('Novel, tragedy', 'romance, tragédia');
INSERT INTO genres (genre, genre_pt) VALUES ('Gothic novel', 'novel gótico');
INSERT INTO genres (genre, genre_pt) VALUES ('Dystopian, political fiction, social science fiction', 'distópico, ficção política, ficção científica social');
INSERT INTO genres (genre, genre_pt) VALUES ('Fiction', 'ficção');
INSERT INTO genres (genre, genre_pt) VALUES ('Young adult fiction', 'ficção adulta jovem');
INSERT INTO genres (genre, genre_pt) VALUES ('Young adult historical novel', 'romance histórico para jovens adultos');
INSERT INTO genres (genre, genre_pt) VALUES ('Self-help, motivational, business fable, psychology, leadership, parable', 'autoajuda, motivacional, fábula comercial, psicologia, liderança, parábola');
INSERT INTO genres (genre, genre_pt) VALUES ('Popular science', 'ciência popular');
INSERT INTO genres (genre, genre_pt) VALUES ('Biographical novel', 'romance biográfico');
INSERT INTO genres (genre, genre_pt) VALUES ('New-age spiritual novel', 'novo espiritual da nova era');
INSERT INTO genres (genre, genre_pt) VALUES ('Young adult romantic novel', 'romance romântico para jovens adultos');
INSERT INTO genres (genre, genre_pt) VALUES ('Thriller', 'filme de ação');
INSERT INTO genres (genre, genre_pt) VALUES ('Crime novel', 'romance criminal');
INSERT INTO genres (genre, genre_pt) VALUES ('Romance novel', 'romance romance');
INSERT INTO genres (genre, genre_pt) VALUES ('Young Adult novel, adventure, dystopian, science fiction', 'romance adulto jovem, aventura, distópico, ficção científica');
INSERT INTO genres (genre, genre_pt) VALUES ('Young Adult novel, adventure, war, science fiction, action thriller', 'romance adulto jovem, aventura, guerra, ficção científica, thriller de ação');
INSERT INTO genres (genre, genre_pt) VALUES ('Japanese novel', 'romance japonês');
INSERT INTO genres (genre, genre_pt) VALUES ('Science fiction novel', 'romance de ficção científica');
INSERT INTO genres (genre, genre_pt) VALUES ('Autobiography', 'autobiografia');
INSERT INTO genres (genre, genre_pt) VALUES ('Crime thriller novel', 'romance de thriller criminal');
INSERT INTO genres (genre, genre_pt) VALUES ('War novel', 'romance de guerra');
INSERT INTO genres (genre, genre_pt) VALUES ('Unknown', 'desconhecido');
INSERT INTO genres (genre, genre_pt) VALUES ('Satirical allegorical novella, Political satire, Dystopian Fiction, Roman à clef', 'novella alegórica satírica, sátira política, ficção distópica, romana à clave');
INSERT INTO genres (genre, genre_pt) VALUES ('Semi-autobiographical novel', 'novel semi-autobiográfico');
INSERT INTO genres (genre, genre_pt) VALUES ('Memoir', 'memórias');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s literature, picture book, fiction', 'literatura infantil, livro de figuras, ficção');
INSERT INTO genres (genre, genre_pt) VALUES ('Feminist novel', 'romance feminista');
INSERT INTO genres (genre, genre_pt) VALUES ('Pregnancy guide', 'guia de gravidez');
INSERT INTO genres (genre, genre_pt) VALUES ('Picaresque novel, Bildungsroman, satire, Robinsonade', 'novelas picaresque, armas de educação, sátira, robinsonada');
INSERT INTO genres (genre, genre_pt) VALUES ('Young adult novel', 'romance para jovens adultos');
INSERT INTO genres (genre, genre_pt) VALUES ('Classic regency novel, romance', 'romance de regência clássica, romance');
INSERT INTO genres (genre, genre_pt) VALUES ('Travel literature', 'literatura de viagem');
INSERT INTO genres (genre, genre_pt) VALUES ('Unfinished satirical dark comedy novel', 'romance de comédia escura satírica inacabada');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s picture book', 'livro de figuras infantis');
INSERT INTO genres (genre, genre_pt) VALUES ('Romantic novel', 'novel romântico');
INSERT INTO genres (genre, genre_pt) VALUES ('Children''s fantasy novel', 'romance de fantasia infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('Social Science, Anthropology, Psychology', 'ciências sociais, antropologia, psicologia');
INSERT INTO genres (genre, genre_pt) VALUES ('Coming-of-age Murder mystery', 'mistério de assassinato de maior idade');
INSERT INTO genres (genre, genre_pt) VALUES ('Autobiographical novel', 'novel autobiográfico');
INSERT INTO genres (genre, genre_pt) VALUES ('Young Adult Fiction', 'ficção adulta jovem');
INSERT INTO genres (genre, genre_pt) VALUES ('Historical fiction, war novel', 'ficção histórica, romance de guerra');
INSERT INTO genres (genre, genre_pt) VALUES ('Erotica', 'erótica');
INSERT INTO genres (genre, genre_pt) VALUES ('Science fiction', 'ficção científica');
INSERT INTO genres (genre, genre_pt) VALUES ('Dystopian fiction', 'ficção distópica');
INSERT INTO genres (genre, genre_pt) VALUES ('Horror', 'horror');
