INSERT INTO authors (name) VALUES ('Charles Dickens');
INSERT INTO authors (name) VALUES ('Antoine de Saint-Exupéry');
INSERT INTO authors (name) VALUES ('J. K. Rowling');
INSERT INTO authors (name) VALUES ('Agatha Christie');
INSERT INTO authors (name) VALUES ('Cao Xueqin');
INSERT INTO authors (name) VALUES ('J. R. R. Tolkien');
INSERT INTO authors (name) VALUES ('C. S. Lewis');
INSERT INTO authors (name) VALUES ('H. Rider Haggard');
INSERT INTO authors (name) VALUES ('Ved Prakash Sharma');
INSERT INTO authors (name) VALUES ('Dan Brown');
INSERT INTO authors (name) VALUES ('Paulo Coelho');
INSERT INTO authors (name) VALUES ('J. D. Salinger');
INSERT INTO authors (name) VALUES ('Robert James Waller');
INSERT INTO authors (name) VALUES ('Lew Wallace');
INSERT INTO authors (name) VALUES ('Louise Hay');
INSERT INTO authors (name) VALUES ('Gabriel García Márquez');
INSERT INTO authors (name) VALUES ('Vladimir Nabokov');
INSERT INTO authors (name) VALUES ('Johanna Spyri');
INSERT INTO authors (name) VALUES ('Benjamin Spock');
INSERT INTO authors (name) VALUES ('Lucy Maud Montgomery');
INSERT INTO authors (name) VALUES ('Anna Sewell');
INSERT INTO authors (name) VALUES ('Umberto Eco');
INSERT INTO authors (name) VALUES ('Jack Higgins');
INSERT INTO authors (name) VALUES ('Richard Adams');
INSERT INTO authors (name) VALUES ('Shere Hite');
INSERT INTO authors (name) VALUES ('E. B. White; illustrated by Garth Williams');
INSERT INTO authors (name) VALUES ('J. P. Donleavy');
INSERT INTO authors (name) VALUES ('Beatrix Potter');
INSERT INTO authors (name) VALUES ('Richard Bach');
INSERT INTO authors (name) VALUES ('Eric Carle');
INSERT INTO authors (name) VALUES ('Elbert Hubbard');
INSERT INTO authors (name) VALUES ('Harper Lee');
INSERT INTO authors (name) VALUES ('V. C. Andrews');
INSERT INTO authors (name) VALUES ('Carl Sagan');
INSERT INTO authors (name) VALUES ('Jostein Gaarder');
INSERT INTO authors (name) VALUES ('Jeffrey Archer');
INSERT INTO authors (name) VALUES ('Nikolai Ostrovsky');
INSERT INTO authors (name) VALUES ('Leo Tolstoy');
INSERT INTO authors (name) VALUES ('Carlo Collodi');
INSERT INTO authors (name) VALUES ('Anne Frank');
INSERT INTO authors (name) VALUES ('Wayne Dyer');
INSERT INTO authors (name) VALUES ('Colleen McCullough');
INSERT INTO authors (name) VALUES ('Rick Warren');
INSERT INTO authors (name) VALUES ('Khaled Hosseini');
INSERT INTO authors (name) VALUES ('Jacqueline Susann');
INSERT INTO authors (name) VALUES ('Bill Wilson');
INSERT INTO authors (name) VALUES ('Dale Carnegie');
INSERT INTO authors (name) VALUES ('F. Scott Fitzgerald');
INSERT INTO authors (name) VALUES ('Margaret Mitchell');
INSERT INTO authors (name) VALUES ('Daphne du Maurier');
INSERT INTO authors (name) VALUES ('George Orwell');
INSERT INTO authors (name) VALUES ('William Bradford Huie');
INSERT INTO authors (name) VALUES ('Stieg Larsson');
INSERT INTO authors (name) VALUES ('Suzanne Collins');
INSERT INTO authors (name) VALUES ('Roald Dahl');
INSERT INTO authors (name) VALUES ('Alexander Alexandrovich Fadeyev');
INSERT INTO authors (name) VALUES ('Spencer Johnson');
INSERT INTO authors (name) VALUES ('Stephen Hawking');
INSERT INTO authors (name) VALUES ('Jacques-Henri Bernardin de Saint-Pierre');
INSERT INTO authors (name) VALUES ('Irving Stone');
INSERT INTO authors (name) VALUES ('Kenneth Grahame');
INSERT INTO authors (name) VALUES ('Stephen R. Covey');
INSERT INTO authors (name) VALUES ('Mikhail Sholokhov');
INSERT INTO authors (name) VALUES ('James Redfield');
INSERT INTO authors (name) VALUES ('John Green');
INSERT INTO authors (name) VALUES ('Paula Hawkins');
INSERT INTO authors (name) VALUES ('William P. Young');
INSERT INTO authors (name) VALUES ('Sergey Mikhalkov');
INSERT INTO authors (name) VALUES ('Mario Puzo');
INSERT INTO authors (name) VALUES ('Erich Segal');
INSERT INTO authors (name) VALUES ('Banana Yoshimoto');
INSERT INTO authors (name) VALUES ('Ivan Yefremov');
INSERT INTO authors (name) VALUES ('Paramahansa Yogananda');
INSERT INTO authors (name) VALUES ('Gillian Flynn');
INSERT INTO authors (name) VALUES ('Erich Maria Remarque');
INSERT INTO authors (name) VALUES ('Charles Berlitz');
INSERT INTO authors (name) VALUES ('Chinua Achebe');
INSERT INTO authors (name) VALUES ('Jiang Rong');
INSERT INTO authors (name) VALUES ('Xaviera Hollander');
INSERT INTO authors (name) VALUES ('Peter Benchley');
INSERT INTO authors (name) VALUES ('Robert Munsch');
INSERT INTO authors (name) VALUES ('Marilyn French');
INSERT INTO authors (name) VALUES ('Arlene Eisenberg and Heidi Murkoff');
INSERT INTO authors (name) VALUES ('Mark Twain');
INSERT INTO authors (name) VALUES ('Sue Townsend');
INSERT INTO authors (name) VALUES ('Jane Austen');
INSERT INTO authors (name) VALUES ('Thor Heyerdahl');
INSERT INTO authors (name) VALUES ('Jaroslav Hašek');
INSERT INTO authors (name) VALUES ('Maurice Sendak');
INSERT INTO authors (name) VALUES ('Norman Vincent Peale');
INSERT INTO authors (name) VALUES ('Rhonda Byrne');
INSERT INTO authors (name) VALUES ('Erica Jong');
INSERT INTO authors (name) VALUES ('Frank Herbert');
INSERT INTO authors (name) VALUES ('Desmond Morris');
INSERT INTO authors (name) VALUES ('Delia Owens');
INSERT INTO authors (name) VALUES ('Tetsuko Kuroyanagi');
INSERT INTO authors (name) VALUES ('Markus Zusak');
INSERT INTO authors (name) VALUES ('Nicholas Evans');
INSERT INTO authors (name) VALUES ('Margaret Wise Brown');
INSERT INTO authors (name) VALUES ('Michael Ende');
INSERT INTO authors (name) VALUES ('Anthony Doerr');
INSERT INTO authors (name) VALUES ('E. L. James');
INSERT INTO authors (name) VALUES ('S. E. Hinton');
INSERT INTO authors (name) VALUES ('Sam McBratney');
INSERT INTO authors (name) VALUES ('James Clavell');
INSERT INTO authors (name) VALUES ('Janette Sebring Lowrey');
INSERT INTO authors (name) VALUES ('Ken Follett');
INSERT INTO authors (name) VALUES ('Patrick Süskind');
INSERT INTO authors (name) VALUES ('John Steinbeck');
INSERT INTO authors (name) VALUES ('Carlos Ruiz Zafón');
INSERT INTO authors (name) VALUES ('Jhumpa Lahiri');
INSERT INTO authors (name) VALUES ('Michelle Obama');
INSERT INTO authors (name) VALUES ('Douglas Adams');
INSERT INTO authors (name) VALUES ('Mitch Albom');
INSERT INTO authors (name) VALUES ('Erskine Caldwell');
INSERT INTO authors (name) VALUES ('Susanna Tamaro');
INSERT INTO authors (name) VALUES ('Madeleine L''Engle');
INSERT INTO authors (name) VALUES ('Nelson Mandela');
INSERT INTO authors (name) VALUES ('Ernest Hemingway');
INSERT INTO authors (name) VALUES ('Raymond Moody');
INSERT INTO authors (name) VALUES ('Grace Metalious');
INSERT INTO authors (name) VALUES ('Lois Lowry');
INSERT INTO authors (name) VALUES ('Jojo Moyes');
INSERT INTO authors (name) VALUES ('Haruki Murakami');
INSERT INTO authors (name) VALUES ('Albert Camus');
INSERT INTO authors (name) VALUES ('Osamu Dazai');
INSERT INTO authors (name) VALUES ('Viktor Frankl');
INSERT INTO authors (name) VALUES ('Dante Alighieri');
INSERT INTO authors (name) VALUES ('Kahlil Gibran');
INSERT INTO authors (name) VALUES ('John Boyne');
INSERT INTO authors (name) VALUES ('William Peter Blatty');
INSERT INTO authors (name) VALUES ('Julia Donaldson');
INSERT INTO authors (name) VALUES ('Astrid Lindgren');
INSERT INTO authors (name) VALUES ('Dr. Seuss');
INSERT INTO authors (name) VALUES ('Andrew Morton');
INSERT INTO authors (name) VALUES ('Kathryn Stockett');
INSERT INTO authors (name) VALUES ('Joseph Heller');
INSERT INTO authors (name) VALUES ('Alice Sebold');
INSERT INTO authors (name) VALUES ('Jung Chang');
INSERT INTO authors (name) VALUES ('Tomás Eloy Martínez');
INSERT INTO authors (name) VALUES ('Elie Wiesel');
INSERT INTO authors (name) VALUES ('Yu Dan');
INSERT INTO authors (name) VALUES ('Marabel Morgan');
INSERT INTO authors (name) VALUES ('Taichi Sakaiya');
INSERT INTO authors (name) VALUES ('Xue Muqiao');
INSERT INTO authors (name) VALUES ('Richard Nelson Bolles');
INSERT INTO authors (name) VALUES ('Pierre Dukan');
INSERT INTO authors (name) VALUES ('Alex Comfort');
INSERT INTO authors (name) VALUES ('Robert L. Short');
INSERT INTO authors (name) VALUES ('Mark Manson');
INSERT INTO authors (name) VALUES ('Yann Martel');
INSERT INTO authors (name) VALUES ('Patricia Nell Warren');
INSERT INTO authors (name) VALUES ('Eliyahu M. Goldratt');
INSERT INTO authors (name) VALUES ('Ray Bradbury');
INSERT INTO authors (name) VALUES ('Frank McCourt');
INSERT INTO authors (name) VALUES ('Mohandas Karamchand Gandhi');
INSERT INTO authors (name) VALUES ('Helen Fielding');
