INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('A Tale of Two Cities', 'English', '1859', '1859.00', '1', '1');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Little Prince (Le Petit Prince)', 'French', '1943', '1943.00', '2', '2');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Harry Potter and the Philosopher''s Stone', 'English', '1997', '1997.00', '3', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('And Then There Were None', 'English', '1939', '1939.00', '4', '4');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Dream of the Red Chamber (紅樓夢)', 'Chinese', '1791', '1791.00', '5', '5');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Hobbit', 'English', '1937', '1937.00', '6', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Lion, the Witch and the Wardrobe', 'English', '1950', '1950.00', '7', '6');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('She: A History of Adventure', 'English', '1887', '1887.00', '8', '7');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Vardi Wala Gunda (वर्दी वाला गुंडा)', 'Hindi', '1992', '1992.00', '9', '8');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Da Vinci Code', 'English', '2003', '2003.00', '10', '9');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Harry Potter and the Chamber of Secrets', 'English', '1998', '1998.00', '3', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Harry Potter and the Prisoner of Azkaban', 'English', '1999', '1999.00', '3', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Harry Potter and the Goblet of Fire', 'English', '2000', '2000.00', '3', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Harry Potter and the Order of the Phoenix', 'English', '2003', '2003.00', '3', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Harry Potter and the Half-Blood Prince', 'English', '2005', '2005.00', '3', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Harry Potter and the Deathly Hallows', 'English', '2007', '2007.00', '3', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Alchemist (O Alquimista)', 'Portuguese', '1988', '1988.00', '11', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Catcher in the Rye', 'English', '1951', '1951.00', '12', '10');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Bridges of Madison County', 'English', '1992', '1992.00', '13', '11');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Ben-Hur: A Tale of the Christ', 'English', '1880', '1880.00', '14', '1');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('You Can Heal Your Life', 'English', '1984', '1984.00', '15', '12');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('One Hundred Years of Solitude (Cien años de soledad)', 'Spanish', '1967', '1967.00', '16', '13');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Lolita', 'English', '1955', '1955.00', '17', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Heidi', 'German', '1880', '1880.00', '18', '15');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Common Sense Book of Baby and Child Care', 'English', '1946', '1946.00', '19', '16');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Anne of Green Gables', 'English', '1908', '1908.00', '20', '17');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Black Beauty', 'English', '1877', '1877.00', '21', '18');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Name of the Rose (Il Nome della Rosa)', 'Italian', '1980', '1980.00', '22', '19');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Eagle Has Landed', 'English', '1975', '1975.00', '23', '20');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Watership Down', 'English', '1972', '1972.00', '24', '3');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Hite Report', 'English', '1976', '1976.00', '25', '21');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Charlotte''s Web', 'English', '1952', '1952.00', '26', '15');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Ginger Man', 'English', '1955', '1955.00', '27', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Tale of Peter Rabbit', 'English', '1902', '1902.00', '28', '22');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Jonathan Livingston Seagull', 'English', '1970', '1970.00', '29', '23');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Very Hungry Caterpillar', 'English', '1969', '1969.00', '30', '24');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('A Message to Garcia', 'English', '1899', '1899.00', '31', '25');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('To Kill a Mockingbird', 'English', '1960', '1960.00', '32', '26');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Flowers in the Attic', 'English', '1979', '1979.00', '33', '27');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Cosmos', 'English', '1980', '1980.00', '34', '28');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Sophie''s World (Sofies verden)', 'Norwegian', '1991', '1991.00', '35', '29');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Angels & Demons', 'English', '2000', '2000.00', '10', '30');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Kane and Abel', 'English', '1979', '1979.00', '36', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('How the Steel Was Tempered (Как закалялась сталь)', 'Russian', '1932', '1932.00', '37', '31');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('War and Peace (Война и мир)', 'Russian', '1869', '1869.00', '38', '32');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Adventures of Pinocchio (Le avventure di Pinocchio)', 'Italian', '1881', '1881.00', '39', '6');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Diary of Anne Frank (Het Achterhuis)', 'Dutch', '1947', '1947.00', '40', '33');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Your Erroneous Zones', 'English', '1976', '1976.00', '41', '12');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Thorn Birds', 'English', '1977', '1977.00', '42', '34');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Purpose Driven Life', 'English', '2002', '2002.00', '43', '35');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Kite Runner', 'English', '2003', '2003.00', '44', '36');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Valley of the Dolls', 'English', '1966', '1966.00', '45', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Alcoholics Anonymous Big Book', 'English', '1939', '1939.00', '46', '12');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('How to Win Friends and Influence People', 'English', '1936', '1936.00', '47', '12');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Great Gatsby', 'English', '1925', '1925.00', '48', '37');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Gone with the Wind', 'English', '1936', '1936.00', '49', '1');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Rebecca', 'English', '1938', '1938.00', '50', '38');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Nineteen Eighty-Four', 'English', '1949', '1949.00', '51', '39');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Revolt of Mamie Stover', 'English', '1951', '1951.00', '52', '40');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Girl with the Dragon Tattoo (Män som hatar kvinnor)', 'Swedish', '2005', '2005.00', '53', '40');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Lost Symbol', 'English', '2009', '2009.00', '10', '40');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Hunger Games', 'English', '2008', '2008.00', '54', '41');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('James and the Giant Peach', 'English', '1961', '1961.00', '55', '17');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Young Guard (Молодая гвардия)', 'Russian', '1945', '1945.00', '56', '42');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Who Moved My Cheese?', 'English', '1998', '1998.00', '57', '43');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('A Brief History of Time', 'English', '1988', '1988.00', '58', '44');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Paul et Virginie', 'French', '1788', '1788.00', '59', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Lust for Life', 'English', '1934', '1934.00', '60', '45');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Wind in the Willows', 'English', '1908', '1908.00', '61', '18');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The 7 Habits of Highly Effective People', 'English', '1989', '1989.00', '62', '12');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Virgin Soil Upturned (Поднятая целина)', 'Russian', '1935', '1935.00', '63', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Celestine Prophecy', 'English', '1993', '1993.00', '64', '46');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Fault in Our Stars', 'English', '2012', '2012.00', '65', '47');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Girl on the Train', 'English', '2015', '2015.00', '66', '48');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Shack', 'English', '2007', '2007.00', '67', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Uncle Styopa (Дядя Стёпа)', 'Russian', '1936', '1936.00', '68', '24');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Godfather', 'English', '1969', '1969.00', '69', '49');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Love Story', 'English', '1970', '1970.00', '70', '50');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Catching Fire', 'English', '2009', '2009.00', '54', '51');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Mockingjay', 'English', '2010', '2010.00', '54', '52');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Kitchen (キッチン)', 'Japanese', '1988', '1988.00', '71', '53');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Andromeda Nebula (Туманность Андромеды)', 'Russian', '1957', '1957.00', '72', '54');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Autobiography of a Yogi (योगी कथामृत)', 'Hindi', '1946', '1946.00', '73', '55');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Gone Girl', 'English', '2012', '2012.00', '74', '56');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('All Quiet on the Western Front (Im Westen nichts Neues)', 'German', '1929', '1929.00', '75', '57');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Bermuda Triangle', 'English', '1974', '1974.00', '76', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Things Fall Apart ', 'English', '1958', '1958.00', '77', '14');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Animal Farm ', 'English', '1945', '1945.00', '51', '59');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Wolf Totem (狼图腾)', 'Chinese', '2004', '2004.00', '78', '60');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Happy Hooker: My Own Story', 'English', '1971', '1971.00', '79', '61');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Jaws', 'English', '1974', '1974.00', '80', '48');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Love You Forever', 'English', '1986', '1986.00', '81', '62');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Women''s Room', 'English', '1977', '1977.00', '82', '63');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('What to Expect When You''re Expecting', 'English', '1984', '1984.00', '83', '64');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Adventures of Huckleberry Finn', 'English', '1885', '1885.00', '84', '65');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Secret Diary of Adrian Mole, Aged 13¾', 'English', '1982', '1982.00', '85', '66');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Pride and Prejudice', 'English', '1813', '1813.00', '86', '67');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Kon-Tiki: Across the Pacific in a Raft (Kon-Tiki ekspedisjonen)', 'Norwegian', '1950', '1950.00', '87', '68');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Good Soldier Švejk (Osudy dobrého vojáka Švejka za světové války)', 'Czech', '1923', '1923.00', '88', '69');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Where the Wild Things Are', 'English', '1963', '1963.00', '89', '70');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Power of Positive Thinking', 'English', '1952', '1952.00', '90', '12');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Secret', 'English', '2006', '2006.00', '91', '12');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Fear of Flying', 'English', '1973', '1973.00', '92', '71');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Dune', 'English', '1965', '1965.00', '93', '54');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Charlie and the Chocolate Factory', 'English', '1964', '1964.00', '55', '72');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Naked Ape', 'English', '1968', '1968.00', '94', '73');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Where the Crawdads Sing', 'English', '2018', '2018.00', '95', '74');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Totto-chan, the Little Girl at the Window (窓ぎわのトットちゃん)', 'Japanese', '1981', '1981.00', '96', '75');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Matilda', 'English', '1988', '1988.00', '55', '22');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Book Thief', 'English', '2005', '2005.00', '97', '76');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Horse Whisperer', 'English', '1995', '1995.00', '98', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Goodnight Moon', 'English', '1947', '1947.00', '99', '22');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Neverending Story (Die unendliche Geschichte)', 'German', '1979', '1979.00', '100', '22');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('All the Light We Cannot See', 'English', '2014', '2014.00', '101', '77');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Fifty Shades of Grey', 'English', '2011', '2011.00', '102', '78');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Outsiders', 'English', '1967', '1967.00', '103', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Guess How Much I Love You', 'English', '1994', '1994.00', '104', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Shōgun', 'English', '1975', '1975.00', '105', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Poky Little Puppy', 'English', '1942', '1942.00', '106', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Pillars of the Earth', 'English', '1989', '1989.00', '107', '1');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Perfume (Das Parfum)', 'German', '1985', '1985.00', '108', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Grapes of Wrath', 'English', '1939', '1939.00', '109', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Shadow of the Wind (La sombra del viento)', 'Spanish', '2001', '2001.00', '110', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Interpreter of Maladies', 'English', '2000', '2000.00', '111', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Becoming', 'English', '2018', '2018.00', '112', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Hitchhiker''s Guide to the Galaxy', 'English', '1979', '1979.00', '113', '79');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Tuesdays with Morrie', 'English', '1997', '1997.00', '114', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('God''s Little Acre', 'English', '1933', '1933.00', '115', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Follow Your Heart (Va'' dove ti porta il cuore)', 'Italian', '1994', '1994.00', '116', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('A Wrinkle in Time', 'English', '1962', '1962.00', '117', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Long Walk to Freedom', 'English', '1994', '1994.00', '118', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Old Man and the Sea', 'English', '1952', '1952.00', '119', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Life After Life', 'English', '1975', '1975.00', '120', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Peyton Place ', 'English', '1956', '1956.00', '121', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Giver', 'English', '1993', '1993.00', '122', '80');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Me Before You', 'English', '2012', '2012.00', '123', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Norwegian Wood (ノルウェイの森)', 'Japanese', '1987', '1987.00', '124', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Plague (La Peste)', 'French', '1947', '1947.00', '125', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('No Longer Human (人間失格)', 'Japanese', '1948', '1948.00', '126', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Man''s Search for Meaning (Ein Psychologe erlebt das Konzentrationslager)', 'German', '1946', '1946.00', '127', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Divine Comedy (La Divina Commedia)', 'Italian', '1304', '1304.00', '128', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Prophet', 'English', '1923', '1923.00', '129', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Boy in the Striped Pyjamas', 'English', '2006', '2006.00', '130', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Exorcist', 'English', '1971', '1971.00', '131', '81');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Gruffalo', 'English', '1999', '1999.00', '132', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Fifty Shades Darker', 'English', '2012', '2012.00', '102', '78');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Tobacco Road', 'English', '1932', '1932.00', '115', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Ronia, the Robber''s Daughter', 'Swedish', '1981', '1981.00', '133', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Cat in the Hat', 'English', '1957', '1957.00', '134', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Diana: Her True Story', 'English', '1992', '1992.00', '135', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Help', 'English', '2009', '2009.00', '136', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Catch-22', 'English', '1961', '1961.00', '137', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Stranger (L''Étranger)', 'French', '1942', '1942.00', '125', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Eye of the Needle', 'English', '1978', '1978.00', '107', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Lovely Bones', 'English', '2002', '2002.00', '138', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Wild Swans', 'English', '1992', '1992.00', '139', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Santa Evita', 'Spanish', '1995', '1995.00', '140', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Night (Un di Velt Hot Geshvign)', 'Yiddish', '1958', '1958.00', '141', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Confucius from the Heart (于丹《论语》心得)', 'Chinese', '2006', '2006.00', '142', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Total Woman', 'English', '1974', '1974.00', '143', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Knowledge-value Revolution (知価革命)', 'Japanese', '1985', '1985.00', '144', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Problems in China''s Socialist Economy (中国社会主义经济问题研究)', 'Chinese', '1979', '1979.00', '145', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('What Color Is Your Parachute?', 'English', '1970', '1970.00', '146', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Dukan Diet', 'French', '2000', '2000.00', '147', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Joy of Sex', 'English', '1972', '1972.00', '148', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Gospel According to Peanuts', 'English', '1965', '1965.00', '149', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Subtle Art of Not Giving a Fuck', 'English', '2016', '2016.00', '150', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Life of Pi', 'English', '2001', '2001.00', '151', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Front Runner', 'English', '1974', '1974.00', '152', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Goal', 'English', '1984', '1984.00', '153', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Fahrenheit 451', 'English', '1953', '1953.00', '154', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Angela''s Ashes', 'English', '1996', '1996.00', '155', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('The Story of My Experiments with Truth (સત્યના પ્રયોગો અથવા આત્મકથા)', 'Gujarati', '1929', '1929.00', '156', '58');
INSERT INTO books (book_name, org_lang, year_published, sales, author_id, genre_id) VALUES ('Bridget Jones''s Diary', 'English', '1996', '1996.00', '157', '58');
