INSERT INTO genres (genre, genre_pt) VALUES ('historical fiction', 'ficção histórica');
INSERT INTO genres (genre, genre_pt) VALUES ('novella', 'novela');
INSERT INTO genres (genre, genre_pt) VALUES ('fantasy', 'fantasia');
INSERT INTO genres (genre, genre_pt) VALUES ('mystery', 'mistério');
INSERT INTO genres (genre, genre_pt) VALUES ('family saga', 'saga da família');
INSERT INTO genres (genre, genre_pt) VALUES ('fantasy, children''s fiction', 'fantasia, ficção infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('adventure', 'aventura');
INSERT INTO genres (genre, genre_pt) VALUES ('detective', 'detetive');
INSERT INTO genres (genre, genre_pt) VALUES ('mystery thriller', 'thriller misterioso');
INSERT INTO genres (genre, genre_pt) VALUES ('coming-of-age', 'amadurecimento');
INSERT INTO genres (genre, genre_pt) VALUES ('romance', 'romance');
INSERT INTO genres (genre, genre_pt) VALUES ('self-help', 'autoajuda');
INSERT INTO genres (genre, genre_pt) VALUES ('magic realism', 'realismo mágico');
INSERT INTO genres (genre, genre_pt) VALUES ('novel', 'romance');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s fiction', 'ficção infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('manual', 'manual');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s novel', 'romance infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s literature', 'literatura infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('historical novel, mystery', 'novel histórico, mystery');
INSERT INTO genres (genre, genre_pt) VALUES ('war, thriller', 'guerra, suspense');
INSERT INTO genres (genre, genre_pt) VALUES ('sexology', 'sexologia');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s literature', 'literatura infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('novella, self-help', 'novella, auto-ajuda');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s literature, picture book', 'literatura infantil, livro de figuras');
INSERT INTO genres (genre, genre_pt) VALUES ('essay/literature', 'ensaio/literatura');
INSERT INTO genres (genre, genre_pt) VALUES ('southern gothic, bildungsroman', 'romance gótico do sul e educacional');
INSERT INTO genres (genre, genre_pt) VALUES ('gothic horror, family saga', 'horror gótico, saga da família');
INSERT INTO genres (genre, genre_pt) VALUES ('popular science, anthropology, astrophysics, cosmology, philosophy, history', 'ciência popular, antropologia, astrofísica, cosmologia, filosofia, história');
INSERT INTO genres (genre, genre_pt) VALUES ('philosophical novel, young adult', 'romance filosófico, jovem adulto');
INSERT INTO genres (genre, genre_pt) VALUES ('mystery-thriller', 'thriller de mistério');
INSERT INTO genres (genre, genre_pt) VALUES ('socialist realist novel', 'romance realista socialista');
INSERT INTO genres (genre, genre_pt) VALUES ('historical novel', 'romance histórico');
INSERT INTO genres (genre, genre_pt) VALUES ('historical non-fiction, autobiography, memoir, bildungsroman / coming of age, jewish literature', 'não ficção histórica, autobiografia, memórias, bildungsroman / withing of age, literatura judaica');
INSERT INTO genres (genre, genre_pt) VALUES ('romantic family saga', 'saga da família romântica');
INSERT INTO genres (genre, genre_pt) VALUES ('christian literature', 'literatura cristã');
INSERT INTO genres (genre, genre_pt) VALUES ('bildungsroman, historical fiction', 'romance educacional, ficção histórica');
INSERT INTO genres (genre, genre_pt) VALUES ('novel, tragedy', 'romance, tragédia');
INSERT INTO genres (genre, genre_pt) VALUES ('gothic novel', 'novel gótico');
INSERT INTO genres (genre, genre_pt) VALUES ('dystopian, political fiction, social science fiction', 'distópico, ficção política, ficção científica social');
INSERT INTO genres (genre, genre_pt) VALUES ('fiction', 'ficção');
INSERT INTO genres (genre, genre_pt) VALUES ('young adult fiction', 'ficção adulta jovem');
INSERT INTO genres (genre, genre_pt) VALUES ('young adult historical novel', 'romance histórico para jovens adultos');
INSERT INTO genres (genre, genre_pt) VALUES ('self-help, motivational, business fable, psychology, leadership, parable', 'autoajuda, motivacional, fábula comercial, psicologia, liderança, parábola');
INSERT INTO genres (genre, genre_pt) VALUES ('popular science', 'ciência popular');
INSERT INTO genres (genre, genre_pt) VALUES ('biographical novel', 'romance biográfico');
INSERT INTO genres (genre, genre_pt) VALUES ('new-age spiritual novel', 'novo espiritual da nova era');
INSERT INTO genres (genre, genre_pt) VALUES ('young adult romantic novel', 'romance romântico para jovens adultos');
INSERT INTO genres (genre, genre_pt) VALUES ('thriller', 'filme de ação');
INSERT INTO genres (genre, genre_pt) VALUES ('crime novel', 'romance criminal');
INSERT INTO genres (genre, genre_pt) VALUES ('romance novel', 'romance romance');
INSERT INTO genres (genre, genre_pt) VALUES ('young adult novel, adventure, dystopian, science fiction', 'romance adulto jovem, aventura, distópico, ficção científica');
INSERT INTO genres (genre, genre_pt) VALUES ('young adult novel, adventure, war, science fiction, action thriller', 'romance adulto jovem, aventura, guerra, ficção científica, thriller de ação');
INSERT INTO genres (genre, genre_pt) VALUES ('japanese novel', 'romance japonês');
INSERT INTO genres (genre, genre_pt) VALUES ('science fiction novel', 'romance de ficção científica');
INSERT INTO genres (genre, genre_pt) VALUES ('autobiography', 'autobiografia');
INSERT INTO genres (genre, genre_pt) VALUES ('crime thriller novel', 'romance de thriller criminal');
INSERT INTO genres (genre, genre_pt) VALUES ('war novel', 'romance de guerra');
INSERT INTO genres (genre, genre_pt) VALUES ('unknown', 'desconhecido');
INSERT INTO genres (genre, genre_pt) VALUES ('satirical allegorical novella, political satire, dystopian fiction, roman à clef', 'novella alegórica satírica, sátira política, ficção distópica, romana à clave');
INSERT INTO genres (genre, genre_pt) VALUES ('semi-autobiographical novel', 'novel semi-autobiográfico');
INSERT INTO genres (genre, genre_pt) VALUES ('memoir', 'memórias');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s literature, picture book, fiction', 'literatura infantil, livro de figuras, ficção');
INSERT INTO genres (genre, genre_pt) VALUES ('feminist novel', 'romance feminista');
INSERT INTO genres (genre, genre_pt) VALUES ('pregnancy guide', 'guia de gravidez');
INSERT INTO genres (genre, genre_pt) VALUES ('picaresque novel, bildungsroman, satire, robinsonade', 'novelas picaresque, armas de educação, sátira, robinsonada');
INSERT INTO genres (genre, genre_pt) VALUES ('young adult novel', 'romance para jovens adultos');
INSERT INTO genres (genre, genre_pt) VALUES ('classic regency novel, romance', 'romance de regência clássica, romance');
INSERT INTO genres (genre, genre_pt) VALUES ('travel literature', 'literatura de viagem');
INSERT INTO genres (genre, genre_pt) VALUES ('unfinished satirical dark comedy novel', 'romance de comédia escura satírica inacabada');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s picture book', 'livro de figuras infantis');
INSERT INTO genres (genre, genre_pt) VALUES ('romantic novel', 'novel romântico');
INSERT INTO genres (genre, genre_pt) VALUES ('children''s fantasy novel', 'romance de fantasia infantil');
INSERT INTO genres (genre, genre_pt) VALUES ('social science, anthropology, psychology', 'ciências sociais, antropologia, psicologia');
INSERT INTO genres (genre, genre_pt) VALUES ('coming-of-age murder mystery', 'mistério de assassinato de maior idade');
INSERT INTO genres (genre, genre_pt) VALUES ('autobiographical novel', 'novel autobiográfico');
INSERT INTO genres (genre, genre_pt) VALUES ('young adult fiction', 'ficção adulta jovem');
INSERT INTO genres (genre, genre_pt) VALUES ('historical fiction, war novel', 'ficção histórica, romance de guerra');
INSERT INTO genres (genre, genre_pt) VALUES ('erotica', 'erótica');
INSERT INTO genres (genre, genre_pt) VALUES ('science fiction', 'ficção científica');
INSERT INTO genres (genre, genre_pt) VALUES ('dystopian fiction', 'ficção distópica');
INSERT INTO genres (genre, genre_pt) VALUES ('horror', 'horror');
